export const ADD_ISSUE = 'ADD_ISSUE';
export const COMPLETE_ISSUE = 'COMPLETE_ISSUE';
export const TOGGLE_FILTER = 'TOGGLE_FILTER';
export const TOGGLE_EDIT = 'TOGGLE_EDIT';
export const REMOVE_ISSUE = 'REMOVE_ISSUE';
export const TOGGLE_ISSUE_STAR = 'TOGGLE_ISSUE_STAR';
